name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Notify Slack
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        name=$(basename -s .git $(git config --get remote.origin.url))
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        curl -X POST --data-urlencode "payload={\"channel\": \"#autolistings\", \"username\": \"Bot\", \"text\": \"New version $tag for $name has been just released!\", \"icon_emoji\": \":tada:\"}" ${{ secrets.SLACK_WEBHOOK }}